### PR TITLE
Drag and drop source code and tests for `poetry-semver`

### PR DESCRIPTION
**Pull request by valeriupredoi**
@carlio and myself had a discussion in https://github.com/landscapeio/requirements-detector/issues/43 and the consensus was to bring over the code from the now-archived `poetry-semver` here. This is the PR that does that.

@carlio mate, I still need to check the dependencies that `requirements-detector` will need from porting the `poetry-semver` code here, but by-and-large the thing works (provided one has `pytest`, I ran the tests and they run fine). Cheers muchly for your support :beer:

### CODE REVIEW

**Comment by carlio** [comment]
Pytest is already a dev dependency for CI so that shouldn't be a problem, and the build pipeline seems to pass so it all looks good to me. 

I'll leave it a little as it seems you're still adding changes.

**Comment by carlio** [comment]
Oh almost - seems like you haven't run the `pre-commit` checks - see https://github.com/landscapeio/requirements-detector/actions/runs/4755989224/jobs/8450928169?pr=45

You just need to do `pre-commit install` and it adds git hooks to automatically run linting and formatters when you commit.

You can also manually run it with `pre-commit run --all`. It'll probably just reformat some of the code

**Comment by valeriupredoi** [comment]
wonderful, many thanks @carlio :beer: I should be done now but I am not 100% sure about editing the `poetry.lock` file - `poetry-semver` is still listed there, and am not very familiar with poetry myself, is that file recreated dynamically? Also, the precommit check is failing, should I fix that?

**Comment by carlio** [comment]
For `poetry.lock`, I suspect that you just manually deleted the `poetry-semver` line from the `pyproject.toml`? In that case run `poetry lock` and it will update the file with the new version constraints (that is, remove poetry-semver)

It's a bit of a hassle, for future reference the best way to do things is to do `poetry remove whatever-dependency` and it'll update the lock file at the same time.

**Comment by valeriupredoi** [comment]
OK mate, I ran the regen of the poetry lock file and pre-commit (black and isort andd all others passed yay!) - I reckon we're good to go :beers:

**Comment by carlio** [comment]
Ok! Seems some files still need formatting but no worries, I will merge anyway because I will need to update the version and do an upload with the new code anyway, so I'll fix any missing pre-commit issues at the same time.

Cheers for the PR and thanks for your understanding about not wanting to add poetry as a dependency!

**Comment by carlio** [comment]
wait never mind yanking that, the tests failed

**Comment by valeriupredoi** [comment]
> @valeriupredoi Here is your shiny new 1.2.0 release - https://pypi.org/project/requirements-detector/1.2.0/

holy cow, that was fast! Brilliant, very many thanks, mate! On to conda forge now :grin:

**Comment by carlio** [comment]
Sorry I should have checked the CI output. The test ran for me locally because I still had the poetry-semver package installed. Gimme a minute!

**Comment by valeriupredoi** [comment]
it's three of them in
```
./requirements_detector/poetry_semver/version_range.py:import semver
./requirements_detector/poetry_semver/version_union.py:import semver
./requirements_detector/poetry_semver/version_constraint.py:import semver
```

**Comment by carlio** [comment]
No worries I should have double checked the CI output, I forgot my local environment would not be completely clean.

Anyway I fixed it - just added the `semver` repo as a dependency and it's all working now.

version `1.2.1` is now on PyPI. Crisis averted :-)

**Comment by carlio** [comment]
All good, I shall go to bed now content with a new release :+1:

**Comment by valeriupredoi** [comment]
sleep well, mate :crescent_moon:

**Pull request merged**
